# Generated by Django 6.0.dev20250710163300 on 2025-10-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_seed_categories_assign_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
